# .github/workflows/python-ci.yml
name: Python CI

on:
  push:
    branches:
      - yjz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          poetry init

      - name: Run tests
        run: |
          python manage.py check
