# .github/workflows/python-ci.yml
name: Python CI

on:
  push:
    branches:
      - yjz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Remove existing poetry.lock and install dependencies
        run: |
          poetry install --no-interaction --no-root --with dev

      - name: Run tests
        run: |
          poetry run python manage.py check
